import type { NextPage } from 'next'
<<<<<<< HEAD
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import VideoGrid from '../components/VideoGrid/VideoGrid'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
=======
import Head from 'next/head'
import VideoGrid from '../components/VideoGrid/VideoGrid'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

>>>>>>> 19cd75bae90ec5ef68c38a34f223afc7125b8bba
      <main>
        <VideoGrid />
      </main>
    </div>
  )
}

export default Home
