name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update depencencies
        run: npm ci

      - name: Build
        run: npm build

      - name: Testing
        run: npm test