name: Build
on:
  push:
    branches:
      - master
      - develop
      - feature/**
  pull_request:
    branches:
      - master
      - develop
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install depencencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run e2e:headless
