name: Docker

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: docker build -t web-video-editor .
