name: Lint
on:
  push:
    branches:
      - master
      - develop
      - feature/**
  pull_request:
    branches:
      - master
      - develop
      - feature/**

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
